from selenium.webdriver.common.by import By

class UrbanRoutesLocators:
    from_field = (By.CSS_SELECTOR, '#from')
    to_field = (By.CSS_SELECTOR, '#to')
    request_taxi_button = (By.CLASS_NAME, "button round")
    comfort_tariff_button = (By.CSS_SELECTOR, '#root')
    phone_modal_button = (By.CLASS_NAME, 'np-text')
    phone_input = (By.ID, 'phone')
    number = (By.XPATH, '//*[@id="phone"]')
    next_button = (By.XPATH, '//*[text()="Siguiente"]')
    click_code = (By.ID, 'code_input')
    code = (By.ID, 'code')
    select_taxi = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[3]/div[1]/button')
    phone_send_button = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[1]/form/div[2]/button')
    payment_method = (By.CLASS_NAME, "pp-button")
    add_card_button = (By.CLASS_NAME, "pp-plus")
    credit_click = (By.CLASS_NAME, 'card-number-input')
    add_credit_card = (By.XPATH, '//*[@id="number"]')
    card_cvv = (By.XPATH, '//div[@class="card-code-input"]/input[@id="code"]')
    agree_card = (By.XPATH, '//*[text()="Agregar"]')
    x_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    cell_next = (By.XPATH, '//*[text()="Confirmar"]')
    driver_message_input = (By.XPATH, '//*[@id="comment"]')
    requests_button = (By.CLASS_NAME, "reqs-head")
    blanket_and_tissues_button = (
    By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span')
    ice_cream_button = (By.CLASS_NAME, "counter-plus")
    taxi_search_button = (By.CLASS_NAME, "smart-button-main")
    modal_taxi = (By.CLASS_NAME, "order-details")